In [9]:
import pandas as pd

In [13]:
df = pd.read_csv("movies.csv")
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [15]:
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [20]:
df.sample(8)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English

In [26]:
df[2:7]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English

In [30]:
df.shape

(37, 10)

In [34]:
df.imdb_rating.min(), df.imdb_rating.max(), df.imdb_rating.mean()

(1.9, 9.3, 7.919444444444445)

In [37]:
df_b = df[df.industry == "Bollywood"]
df_h = df[df.industry == "Hollywood"]

In [38]:
df_b

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.0,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.4,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.0,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [39]:
df_h

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English

In [40]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'budget',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'currency',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'imdb_rating',
 'index',
 'industry',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'language',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'release_year',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'revenue',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'studio',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'title',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unit',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [41]:
df_b.imdb_rating.min(), df_b.imdb_rating.max(), df_b.imdb_rating.mean()

(1.9, 8.4, 7.656250000000001)

In [42]:
df_h.imdb_rating.min(), df_h.imdb_rating.max(), df_h.imdb_rating.mean()

(6.8, 9.3, 8.130000000000003)

In [51]:
df = pd.read_csv("movies.csv")
print("All movies: Min=", df.imdb_rating.min(), "Max=", df.imdb_rating.max() , "Avg=",df.imdb_rating.mean())

df_b = df[df.industry == "Bollywood"]
df_h = df[df.industry == "Hollywood"]

print("Bollywood: Min=", df_b.imdb_rating.min(), "Max=", df_b.imdb_rating.max(), "Avg=", df_b.imdb_rating.mean())
print("Hollywood: Min=", df_h.imdb_rating.min(), "Max=", df_h.imdb_rating.max(), "Avg=", df_h.imdb_rating.mean())

All movies: Min= 1.9 Max= 9.3 Avg= 7.919444444444445
Bollywood: Min= 1.9 Max= 8.4 Avg= 7.656250000000001
Hollywood: Min= 6.8 Max= 9.3 Avg= 8.130000000000003